### ISSUE TITLE
26/03

### ISSUE THREAD

**Issue by SevlaMare** [harshdeep-kanhai/new-york-time-article#1]

**Comment by SevlaMare** [comment]
-Avoid use more than 3 selectors nested, is a bad practice, because each additional selector will be a new nested loop, like in line 220 (.footer .nav ul li a).
-In places like in navbar, you can use flex properties instead of bootstrap grid, see more on https://getbootstrap.com/docs/4.4/utilities/flex/

**Comment by ghamtre** [comment]
Create a new class for the footer, delete everything else so you can start from zero and figure it out the problem with your footer at the top.

**Comment by harshdeep-kanhai** [comment]
* Now made nested selector to max 3.
* Fixed the footer
